const BASE_PANEL_ENEMIES = [
  { id:'slime', name:'スライム', emoji:'🟢', hp:80, atk:12, resistPhys:0, resistMagic:0, expBase:20, goldBase:40 },
  { id:'bat', name:'コウモリ', emoji:'🦇', hp:70, atk:14, resistPhys:-0.1, resistMagic:0.1, expBase:22, goldBase:45 },
  { id:'skeleton', name:'スケルトン', emoji:'💀', hp:95, atk:16, resistPhys:0.2, resistMagic:-0.2, expBase:26, goldBase:55 }
];

const SUGOROKU_STAGES = {
  1:{ name:"始まりの草原", desc:"穏やかな平原エリア。", level:10, bg:"images/bg_iconstage1.webp", battleBg:"images/bg_battle_grass.webp", totalEncounters:12, midbossAt:6, enemyLv:5, bossLv:10, bossId:2, sugorokuBattleBg:"images/bg_stage1.webp", bgPath:"images/stage/stage1/", layers:[{file:'layer1.webp',speed:0,isFront:false},{file:'layer2.webp',speed:0.1,isFront:false},{file:'layer3.webp',speed:0.3,isFront:false},{file:'layer4.webp',speed:0.6,isFront:false},{file:'layer5.webp',speed:1.0,isFront:false},{file:'layer6.webp',speed:1.2,isFront:true}], panelEnemies: BASE_PANEL_ENEMIES },
  2:{ name:"迷いの森", desc:"深い霧に包まれた森。", level:20, bg:"images/bg_iconstage2.webp", battleBg:"images/bg_battle_forest.webp", totalEncounters:13, midbossAt:7, enemyLv:12, bossLv:20, bossId:13, sugorokuBattleBg:"images/bg_stage2.webp", bgPath:"images/stage/stage2/", layers:[{file:'layer1.webp',speed:0,isFront:false},{file:'layer2.webp',speed:0.1,isFront:false},{file:'layer3.webp',speed:0.3,isFront:false},{file:'layer4.webp',speed:0.6,isFront:false},{file:'layer5.webp',speed:1.0,isFront:false},{file:'layer6.webp',speed:1.2,isFront:true}], panelEnemies: BASE_PANEL_ENEMIES },
  3:{ name:"古代遺跡", desc:"罠が眠る遺跡。", level:30, bg:"images/bg_iconstage3.webp", battleBg:"images/bg_battle_ruins.webp", totalEncounters:14, midbossAt:7, enemyLv:20, bossLv:30, bossId:24, sugorokuBattleBg:"images/bg_stage3.webp", bgPath:"images/stage/stage3/", layers:[{file:'layer1.webp',speed:0,isFront:false},{file:'layer2.webp',speed:0.1,isFront:false},{file:'layer3.webp',speed:0.3,isFront:false},{file:'layer4.webp',speed:0.6,isFront:false},{file:'layer5.webp',speed:1.0,isFront:false},{file:'layer6.webp',speed:1.2,isFront:true}], panelEnemies: BASE_PANEL_ENEMIES },
  4:{ name:"灼熱の火山", desc:"炎の魔物が棲む。", level:40, bg:"images/bg_iconstage4.webp", battleBg:"images/bg_battle_grass.webp", totalEncounters:14, midbossAt:8, enemyLv:28, bossLv:40, bossId:54, sugorokuBattleBg:"images/bg_stage4.webp", bgPath:"images/stage/stage4/", layers:[{file:'layer1.webp',speed:0,isFront:false},{file:'layer2.webp',speed:0.1,isFront:false},{file:'layer3.webp',speed:0.3,isFront:false},{file:'layer4.webp',speed:0.6,isFront:false},{file:'layer5.webp',speed:1.0,isFront:false},{file:'layer6.webp',speed:1.2,isFront:true}], panelEnemies: BASE_PANEL_ENEMIES },
  5:{ name:"氷雪の峠", desc:"凍てつく吹雪の峠。", level:50, bg:"images/bg_iconstage5.webp", battleBg:"images/bg_battle_forest.webp", totalEncounters:15, midbossAt:8, enemyLv:35, bossLv:50, bossId:43, sugorokuBattleBg:"images/bg_stage5.webp", bgPath:"images/stage/stage5/", layers:[{file:'layer1.webp',speed:0,isFront:false},{file:'layer2.webp',speed:0.1,isFront:false},{file:'layer3.webp',speed:0.3,isFront:false},{file:'layer4.webp',speed:0.6,isFront:false},{file:'layer5.webp',speed:1.0,isFront:false},{file:'layer6.webp',speed:1.2,isFront:true}], panelEnemies: BASE_PANEL_ENEMIES },
  6:{ name:"魔王の城", desc:"禁断の城。", level:60, bg:"images/bg_iconstage6.webp", battleBg:"images/bg_battle_ruins.webp", totalEncounters:16, midbossAt:9, enemyLv:50, bossLv:75, bossId:6, sugorokuBattleBg:"images/bg_stage7.webp", bgPath:"images/stage/stage7/", layers:[{file:'layer1.webp',speed:0,isFront:false},{file:'layer2.webp',speed:0.1,isFront:false},{file:'layer3.webp',speed:0.3,isFront:false},{file:'layer4.webp',speed:0.6,isFront:false},{file:'layer5.webp',speed:1.0,isFront:false},{file:'layer6.webp',speed:1.2,isFront:true}], panelEnemies: BASE_PANEL_ENEMIES },
  7:{ name:"天空の神殿", desc:"伝説の神殿。", level:75, bg:"images/bg_iconstage7.webp", battleBg:"images/bg_battle_grass.webp", totalEncounters:18, midbossAt:10, enemyLv:65, bossLv:90, bossId:14, sugorokuBattleBg:"images/bg_stage7.webp", bgPath:"images/stage/stage7/", layers:[{file:'layer1.webp',speed:0,isFront:false},{file:'layer2.webp',speed:0.1,isFront:false},{file:'layer3.webp',speed:0.3,isFront:false},{file:'layer4.webp',speed:0.6,isFront:false},{file:'layer5.webp',speed:1.0,isFront:false},{file:'layer6.webp',speed:1.2,isFront:true}], panelEnemies: BASE_PANEL_ENEMIES }
};
